services:

  postgres:
    image: postgres:latest
    container_name: devops-pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: healthcheck
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-healthcheck
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: healthcheck

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: devops-ui
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  pgdata:
